# Generated by Django 5.1.7 on 2025-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
