# Generated by Django 5.1.7 on 2025-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_table_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu_quantities',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.IntegerField(),
        ),
    ]
